apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-helm-chart.fullname" . }}-configmap
  labels:
    name: {{ include "simple-helm-chart.fullname" . }}-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>

    <h1>Hello World</h1>

    </body>
    </html>

